version: 2.1

jobs:
  build:
    docker:
      - image: hairyhenderson/gomplate-ci-build:latest
    working_directory: /go/src/github.com/hairyhenderson/github-responder
    steps:
      - checkout
      - run: make build
      - run: cc-test-reporter before-build
      - run:
          name: make test
          command: |
            trap "go-junit-report < /tmp/test-results/go-test.out > /tmp/test-results/report.xml" EXIT
            make test | tee /tmp/test-results/go-test.out
            echo $? > test.exit
      - store_test_results:
          path: /tmp/test-results
      - run: cc-test-reporter after-build --exit-code $(< test.exit)
      - run: make lint
      # - run: make integration
      - store_artifacts:
          path: bin
          destination: binaries
